baseURL = "http://mishochu.com"
title = "Mish Ochu"
theme = "coder" # set the theme


languageCode = "en-us"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params] # theme parameters
    author = "Mish Ochu"
    info = "Still writing, sometimes in code, sometimes in English" # author's job title or info
    description = "Buckle in, this is going to get random" # site description
    keywords = "blog,developer,personal" # site keywords

# Social links
[[params.social]]
    name = "Github"
    weight = 1
    url = "https://github.com/mishfit/"
[[params.social]]
    name = "LinkedIn"
    weight = 2
    url = "https://www.linkedin.com/in/mishochu/"
[[params.social]]
    name = "Twitter"
    weight = 3
    url = "https://twitter.com/mishochu/"

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/posts/"
[[menu.main]]
    name = "About"
    weight = 2
    url = "/about/"
